#!/usr/bin/env python3
"""gen_architecture.py — 自动生成模块依赖图

输出: dashboard/src/data/architecture/deps.mmd  (Mermaid 格式)
      dashboard/src/data/architecture/deps.json (JSON 格式)

每次运行覆盖输出，确保与代码同步。
"""

import ast, json, os, sys
from pathlib import Path
from collections import defaultdict

PROJECT = Path(__file__).parent.parent
SRC_DIRS = ['experts', 'backtest', 'factors', 'config', 'scripts']

# ── 模块分类 ────────────────────────────────────────────────────

CATEGORIES = {
    'experts/orchestrator':     '编排层',
    'experts/specialists/':     '策略层',
    'experts/evaluator':         '评估层',
    'experts/debate_manager':    '评审层',
    'experts/modules/':         '模块层',
    'experts/report_writer':    '报告层',
    'experts/data_loader':      '数据层',
    'backtest/engine':          '回测层',
    'backtest/local_data':      '数据层',
    'backtest/indicators':      '因子层',
    'factors/':                 '因子层',
    'config/':                  '配置层',
    'dashboard/':               '前端',
}

def get_category(filepath: str) -> str:
    for prefix, cat in CATEGORIES.items():
        if filepath.startswith(prefix):
            return cat
    return '其他'

# ── 分析 imports ────────────────────────────────────────────────

def extract_imports(filepath: str) -> list:
    """从 .py 文件中提取内部模块导入"""
    try:
        tree = ast.parse(Path(filepath).read_text())
    except Exception:
        return []

    imports = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.append(node.module)
    return imports

def is_internal(module_name: str) -> bool:
    """判断是否为项目内部模块"""
    prefixes = ['experts', 'backtest', 'factors', 'config', 'scripts']
    return any(module_name.startswith(p) for p in prefixes)

# ── 主流程 ──────────────────────────────────────────────────────

def main():
    edges = defaultdict(set)  # source → {targets}
    node_cats = {}  # node → category label

    # 扫描所有 .py 文件
    py_files = []
    for d in SRC_DIRS:
        py_files.extend((PROJECT / d).rglob('*.py'))

    for f in sorted(py_files):
        rel = str(f.relative_to(PROJECT))
        module = rel.replace('/', '.').replace('.py', '')

        # 跳过 __init__ 和 __pycache__
        if '__' in module:
            continue

        cat = get_category(rel)
        node_cats[module] = cat

        for imp in extract_imports(str(f)):
            if is_internal(imp) and imp != module:
                edges[module].add(imp)

    # ── 生成 Mermaid ────────────────────────────────────────
    mmd_lines = ['graph TD']
    mmd_lines.append('  %% Auto-generated by gen_architecture.py')
    mmd_lines.append('  %% DO NOT EDIT MANUALLY')
    mmd_lines.append('')

    # 子图分组
    groups = defaultdict(list)
    for node, cat in node_cats.items():
        groups[cat].append(node)

    cat_ids = {cat: f'G{i}' for i, cat in enumerate(groups)}

    for cat, nodes in sorted(groups.items()):
        if len(nodes) == 0:
            continue
        mmd_lines.append(f'  subgraph {cat_ids[cat]}["{cat}"]')
        for node in sorted(nodes):
            node_id = node.replace('.', '_').replace('/', '_')
            short = node.split('.')[-1]
            mmd_lines.append(f'    {node_id}["{short}"]')
        mmd_lines.append('  end')
        mmd_lines.append('')

    # 边
    for src, targets in sorted(edges.items()):
        src_id = src.replace('.', '_').replace('/', '_')
        for tgt in sorted(targets):
            tgt_id = tgt.replace('.', '_').replace('/', '_')
            mmd_lines.append(f'  {src_id} --> {tgt_id}')

    # ── 输出 ────────────────────────────────────────────────
    out_dir = PROJECT / 'dashboard' / 'src' / 'data' / 'architecture'
    out_dir.mkdir(parents=True, exist_ok=True)

    mmd = '\n'.join(mmd_lines)
    (out_dir / 'deps.mmd').write_text(mmd)
    print(f'Mermaid diagram: {out_dir / "deps.mmd"} ({len(edges)} edges)')

    # 同时保存 JSON 格式供 Dashboard 使用
    json_data = {
        'nodes': [
            {'id': node.replace('.', '_').replace('/', '_'),
             'label': node.split('.')[-1],
             'fullPath': node,
             'category': cat}
            for node, cat in node_cats.items()
        ],
        'edges': [
            {'source': src.replace('.', '_').replace('/', '_'),
             'target': tgt.replace('.', '_').replace('/', '_')}
            for src, targets in edges.items()
            for tgt in targets
        ]
    }
    (out_dir / 'deps.json').write_text(json.dumps(json_data, ensure_ascii=False, indent=2))
    print(f'JSON data: {out_dir / "deps.json"} ({len(json_data["nodes"])} nodes)')

if __name__ == '__main__':
    main()
